### ISSUE TITLE
NLP - ROS integration

### ISSUE THREAD

**Issue by emnault** [LiamWellacott/CDT2019-ERL#66] opened 2021-02-15 15:19 UTC

**Comment by LiamWellacott** [comment] 2021-02-15 16:26
duplicate of #55?

**Comment by emnault** [comment] 2021-02-15 16:48
> duplicate of #55?

I thought there was more to the ROS integration than hooking up the mic, am i wrong?

**Comment by LiamWellacott** [comment] 2021-02-15 17:03
You will most likely interface with the tiago mic by subscribing to a ROS topic so I think #55 is contained in this issue. You are right this is probably a bigger task than this point though. Up to you how you think makes sense to split the work.

**Comment by LiamWellacott** [comment] 2021-02-15 22:13
Had a look at options, put a comment about the microphone on #55. 

Made a branch (nlp) which has a ROS package for nlp partially implemented (only speaking though, see comment). What is there is based on the [tts package](http://wiki.ros.org/Robots/TIAGo/Tutorials/TTS) which is part of the tiago software we have.

**Comment by emnault** [comment] 2021-02-15 22:39
Thanks for looking into this Liam & for creating the branch. John & I will have a look at it once we finish with Alexa.

**Comment by NicolayP** [comment] 2021-02-25 18:11
This is done, closing the issue as Alexa is now compatible with ros through Flask-ask

**Closed as completed by NicolayP** 2021-02-25 18:11 UTC
Labels: NLP
